version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - symfony_vendor:/var/www/html/vendor
      - symfony_var:/var/www/html/var
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      # Passed into Symfony via .env or .env.local (recommended)
      POSTGRES_HOST: db
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  symfony_vendor:
  symfony_var:
  db_data:
