services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_app
    working_dir: /var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    volumes:
      - ./backend:/var/www/html
      - symfony_var:/var/www/html/var
      - symfony_vendor:/var/www/html/vendor

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    image: node:20-alpine
    container_name: vue_frontend
    working_dir: /app
    # Vite dev server
    command: sh -lc "corepack enable && yarn install && yarn dev --host"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      # Helpful in Docker/Windows so file changes are detected
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

volumes:
  db_data:
  symfony_var:
  symfony_vendor:
